spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdevdb
    username: springdevuser
    password: springdevpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
           non_contextual_creation: true
